### ISSUE TITLE
ENOENT: no such file or directory, open 'redditAPI.json'

### ISSUE THREAD

**Issue by JonaCeja54** [Dallas-1/EmojiPastaGenerator#1]
Hey 🚨 dude, 😎 When 🍑 I 👁 run 🏃 the 👏 scraper I 👁 get 🔟 a 👌 ENOENT error. 🚫 It 💯 can 💦 not 🚫 find 👅 redditAPI.json, Is 💦 that 😐 file missing? I 👁 assume 😮 is 💦 has 👏 the 👏 api keys. maybe 👏 add 😰 a 👌 sample file? 🤔

```
Error: ENOENT: no such file or directory, open 'redditAPI.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.readFileSync (/Users/jonathanalejandrocejagonzalez/Documents/Projects/EmojiPastaGenerator/Scraper/node_modules/jsonfile/index.js:66:20)
    at Object.<anonymous> (/Users/jonathanalejandrocejagonzalez/Documents/Projects/EmojiPastaGenerator/Scraper/ScrapeEmojis.js:6:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

(Sorry, maybe we should drop the emoji pasta here idk how you feel about that)

**Comment by JackDallas** [comment]
Ohh good point, I remember the part where I don't publish my api keys but I forgot the part where I tell others they need them, I'll hop on my laptop and make a sample, ty

**Comment by JackDallas** [comment]
Fixed in https://github.com/Dallas-1/EmojiPastaGenerator/commit/f634c90eb362f68682f75064535751c96ce5c85f

Thanks for reporting 😄
